/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoaviones;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class AdminModif2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminModif2.class.getName());

    public AdminModif2() {
        initComponents();
    }
    
    String ID;
    
    public AdminModif2(String id) {
        initComponents();
        this.setLocationRelativeTo(null);
        ID = id;
        
        consultar(ID);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fecSalida = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        hrsSalida = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        fecLlegada = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        hrsLlegada = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        txtPuertaSalida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPuertaEmbarque = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        msg = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNumVuelo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAvion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(95, 15, 64));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Modificar Vuelo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Destino:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fecha de salida:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Hora de salida:");

        hrsSalida.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.AM_PM));
        hrsSalida.setEditor(new javax.swing.JSpinner.DateEditor(hrsSalida, "HH:mm"));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Fecha de llegada:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Hora de llegada:");

        hrsLlegada.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.AM_PM));
        hrsLlegada.setEditor(new javax.swing.JSpinner.DateEditor(hrsLlegada, "HH:mm"));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Puerta de salida:");

        txtPuertaSalida.addActionListener(this::txtPuertaSalidaActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Puerta de embarque:");

        txtPuertaEmbarque.addActionListener(this::txtPuertaEmbarqueActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Precio:");

        txtPrecio.addActionListener(this::txtPrecioActionPerformed);

        btnModificar.setBackground(new java.awt.Color(95, 15, 64));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("MODIFICAR");
        btnModificar.setToolTipText("");
        btnModificar.setFocusPainted(false);
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Número de vuelo:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Avión:");

        txtAvion.addActionListener(this::txtAvionActionPerformed);

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("186106 - 186831 - 187012");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPuertaSalida)
                                            .addComponent(txtPuertaEmbarque)
                                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fecSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hrsSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fecLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hrsLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNumVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(msg, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36))
                                    .addComponent(fecSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hrsSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hrsLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuertaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuertaEmbarque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPuertaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuertaSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuertaSalidaActionPerformed

    private void txtPuertaEmbarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuertaEmbarqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuertaEmbarqueActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificarVuelo(ID);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminModif2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private com.toedter.calendar.JDateChooser fecLlegada;
    private com.toedter.calendar.JDateChooser fecSalida;
    private javax.swing.JSpinner hrsLlegada;
    private javax.swing.JSpinner hrsSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel msg;
    private javax.swing.JTextField txtAvion;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtNumVuelo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPuertaEmbarque;
    private javax.swing.JTextField txtPuertaSalida;
    // End of variables declaration//GEN-END:variables

    public void consultar(String id){
        
        try (Connection con = DBConn.conectar()) {
        String sql = "SELECT * FROM vuelos WHERE num_vuelo = ?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, id);

        ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                // Llenar JTextFields (Cadenas de texto)
                txtNumVuelo.setText(rs.getString("num_vuelo"));
                txtDestino.setText(rs.getString("destino"));
                txtPuertaSalida.setText(rs.getString("puerta_salida"));
                txtPuertaEmbarque.setText(rs.getString("puerta_embarque"));

                // Llenar Precio (Convertir Double a String)
                txtPrecio.setText(String.valueOf(rs.getDouble("precio")));

                // Llenar JDateChoosers (Fechas): rs.getDate devuelve java.sql.Date, que es compatible con setDate
                fecSalida.setDate(rs.getDate("fecha_salida"));
                fecLlegada.setDate(rs.getDate("fecha_llegada"));

                // Llenar JSpinners (Horas) : rs.getTime devuelve java.sql.Time, que hereda de java.util.Date
                hrsSalida.setValue(rs.getTime("hora_salida"));
                hrsLlegada.setValue(rs.getTime("hora_llegada"));
                txtAvion.setText(rs.getString("num_avion"));

            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al consultar la base de datos.");
        } 
    }
    
    public void modificarVuelo(String id) {

        if (txtNumVuelo.getText().trim().isEmpty() || txtDestino.getText().trim().isEmpty() || 
            fecSalida.getDate() == null || fecLlegada.getDate() == null || 
            txtPuertaSalida.getText().trim().isEmpty() || txtPuertaEmbarque.getText().trim().isEmpty() || 
            txtPrecio.getText().trim().isEmpty() || txtAvion.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Por favor, complete todos los espacios");
            return; 
        }
        
        // Validaciones de formato antes de intentar la conexión
        if (!txtNumVuelo.getText().trim().matches("^MX\\d{3}$")) {
            JOptionPane.showMessageDialog(this, "Formato de número de vuelo inválido (Ej: MX022)");
            return;
        }
        if (!txtDestino.getText().trim().matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$")) {
            JOptionPane.showMessageDialog(this, "El destino solo debe contener letras");
            return;
        }
        if (!txtPrecio.getText().trim().matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número válido");
            return;
        }
        if (txtAvion.getText().trim().length() != 5) {
            JOptionPane.showMessageDialog(this, "Error: El número de avión debe ser de 5 caracteres (ej. BA283)");
            txtAvion.setText("");
            txtAvion.requestFocus();
            return;
        }

        java.util.Date dSalida = fecSalida.getDate();
        java.util.Date tSalida = (java.util.Date) hrsSalida.getValue();
        java.util.Date dLlegada = fecLlegada.getDate();
        
        java.time.LocalDate localDateSalida = dSalida.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        java.time.LocalTime localTimeSalida = tSalida.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalTime();
        java.time.LocalDateTime limiteMinimo = java.time.LocalDateTime.now().plusHours(5);
        
        java.time.LocalDateTime fechaHoraSalida = java.time.LocalDateTime.of(localDateSalida, localTimeSalida);
        java.time.LocalDate hoy = java.time.LocalDate.now();

        if (fechaHoraSalida.isBefore(limiteMinimo)) {
            java.time.format.DateTimeFormatter formatoMensaje = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy hh:mm a");

            JOptionPane.showMessageDialog(this, 
                "Error: Los vuelos deben programarse con al menos 5 horas de anticipación.\n" +
                "La fecha y hora mínima permitida para este vuelo es: " + limiteMinimo.format(formatoMensaje),
                "Horario Inválido",
                JOptionPane.ERROR_MESSAGE);

            fecSalida.setDate(null);
            fecSalida.requestFocus();
            return; // Detiene el registro
        }
        if (dLlegada.before(dSalida)) {
            JOptionPane.showMessageDialog(this, "Error: La llegada no puede ser antes que la salida");
            fecLlegada.setDate(null); // Borra solo la fecha de llegada
            fecLlegada.requestFocus();
            return;
        }
        
        // Formateadores para MySQL
        SimpleDateFormat sdfFecha = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdfHora = new SimpleDateFormat("HH:mm:ss");

        try (Connection con = DBConn.conectar()) {
            
            // Validación para no repetir num_vuelo
            String sqlCheck = "SELECT COUNT(*) FROM vuelos WHERE num_vuelo = ?";
            PreparedStatement psCheck = con.prepareStatement(sqlCheck);
            psCheck.setString(1, id);
            ResultSet rsCheck = psCheck.executeQuery();

            // Leemos el resultado del conteo
            if (rsCheck.next()) {
                int cantidadEncontrada = rsCheck.getInt(1);

                if (cantidadEncontrada > 0) {
                    // Si es mayor a 0, significa que el número ya está ocupado
                    JOptionPane.showMessageDialog(this, 
                        "Error: El número de vuelo " + id + " ya se encuentra registrado en el sistema.", 
                        "Vuelo Duplicado", 
                        JOptionPane.ERROR_MESSAGE);

                    txtNumVuelo.setText("");
                    txtNumVuelo.requestFocus();
                    return; }   }
        

            // Preparar el UPDATE
            String sqlUpdate = "UPDATE vuelos SET num_vuelo=?, destino=?, fecha_salida=?, hora_salida=?, "
                             + "fecha_llegada=?, hora_llegada=?, puerta_salida=?, puerta_embarque=?, "
                             + "precio=? WHERE num_vuelo=?";

            PreparedStatement ps = con.prepareStatement(sqlUpdate);

            ps.setString(1, txtNumVuelo.getText().trim());
            ps.setString(2, txtDestino.getText().trim());
            ps.setString(3, sdfFecha.format(dSalida));
            ps.setString(4, sdfHora.format((java.util.Date) hrsSalida.getValue()));
            ps.setString(5, sdfFecha.format(dLlegada));
            ps.setString(6, sdfHora.format((java.util.Date) hrsLlegada.getValue()));
            ps.setString(7, txtPuertaSalida.getText().trim());
            ps.setString(8, txtPuertaEmbarque.getText().trim());
            ps.setDouble(9, Double.parseDouble(txtPrecio.getText().trim()));
            ps.setString(10, id);

            int resultado = ps.executeUpdate();

            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Vuelo modificado correctamente");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el registro para modificar");
            }

        } catch (SQLException e) {
            if (e.getErrorCode() == 1452) { // Error de llave foránea (Avión no existe)
                JOptionPane.showMessageDialog(this, "Error: El ID de avión ingresado no existe");
            } else {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error de base de datos al modificar");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error inesperado al procesar la modificación");
        }
    }
    
}
