/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoaviones;
import java.sql.*;
import java.awt.Desktop;
import java.io.File;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import java.io.FileOutputStream;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import com.itextpdf.text.Font;

import com.itextpdf.text.Document;
import com.itextpdf.text.Image;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPCell;
import java.util.ArrayList;
import java.util.List;

public class Avion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Avion.class.getName());

    String user,idV;
    int dispo[] = new int[42]; 
    private javax.swing.JToggleButton[] asientos;
    Temp tempo; 
    
    public Avion(String uss, String idVuelo) {
        initComponents();
        this.setLocationRelativeTo(null);
        user = uss;
        idV = idVuelo;
        
        asientos = new javax.swing.JToggleButton[]{
        A1, A2, A3, A4, A5, A6, B1, B2, B3, B4, B5, B6,
        C1, C2, C3, C4, C5, C6, D1, D2, D3, D4, D5, D6,
        E1, E2, E3, E4, E5, E6, F1, F2, F3, F4, F5, F6,
        G1, G2, G3, G4, G5, G6 };
        
        cargarVuelo(idV);
        actualizarMapaAsientos(idV);
        
        tempo = new Temp(this);
        tempo.start();
    }
    
    public Avion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        A1 = new javax.swing.JToggleButton();
        A2 = new javax.swing.JToggleButton();
        A3 = new javax.swing.JToggleButton();
        A4 = new javax.swing.JToggleButton();
        A5 = new javax.swing.JToggleButton();
        A6 = new javax.swing.JToggleButton();
        B1 = new javax.swing.JToggleButton();
        B2 = new javax.swing.JToggleButton();
        B3 = new javax.swing.JToggleButton();
        B4 = new javax.swing.JToggleButton();
        B5 = new javax.swing.JToggleButton();
        B6 = new javax.swing.JToggleButton();
        C1 = new javax.swing.JToggleButton();
        C2 = new javax.swing.JToggleButton();
        C3 = new javax.swing.JToggleButton();
        C4 = new javax.swing.JToggleButton();
        C5 = new javax.swing.JToggleButton();
        C6 = new javax.swing.JToggleButton();
        D1 = new javax.swing.JToggleButton();
        D2 = new javax.swing.JToggleButton();
        D3 = new javax.swing.JToggleButton();
        D4 = new javax.swing.JToggleButton();
        D5 = new javax.swing.JToggleButton();
        D6 = new javax.swing.JToggleButton();
        E1 = new javax.swing.JToggleButton();
        E2 = new javax.swing.JToggleButton();
        E3 = new javax.swing.JToggleButton();
        E4 = new javax.swing.JToggleButton();
        E5 = new javax.swing.JToggleButton();
        E6 = new javax.swing.JToggleButton();
        F1 = new javax.swing.JToggleButton();
        F2 = new javax.swing.JToggleButton();
        F3 = new javax.swing.JToggleButton();
        F4 = new javax.swing.JToggleButton();
        F5 = new javax.swing.JToggleButton();
        F6 = new javax.swing.JToggleButton();
        G1 = new javax.swing.JToggleButton();
        G2 = new javax.swing.JToggleButton();
        G3 = new javax.swing.JToggleButton();
        G4 = new javax.swing.JToggleButton();
        G5 = new javax.swing.JToggleButton();
        G6 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        infovuelo = new javax.swing.JLabel();
        nvuelo = new javax.swing.JLabel();
        pagar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        A1.setBorder(null);
        A1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        A1.addActionListener(this::A1ActionPerformed);

        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        A2.setBorder(null);
        A2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        A2.addActionListener(this::A2ActionPerformed);

        A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        A3.setBorder(null);
        A3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        A3.addActionListener(this::A3ActionPerformed);

        A4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        A4.setBorder(null);
        A4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        A4.addActionListener(this::A4ActionPerformed);

        A5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        A5.setBorder(null);
        A5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        A5.addActionListener(this::A5ActionPerformed);

        A6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        A6.setBorder(null);
        A6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        A6.addActionListener(this::A6ActionPerformed);

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        B1.setBorder(null);
        B1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        B1.addActionListener(this::B1ActionPerformed);

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        B2.setBorder(null);
        B2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        B2.addActionListener(this::B2ActionPerformed);

        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        B3.setBorder(null);
        B3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        B3.addActionListener(this::B3ActionPerformed);

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        B4.setBorder(null);
        B4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        B4.addActionListener(this::B4ActionPerformed);

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        B5.setBorder(null);
        B5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        B5.addActionListener(this::B5ActionPerformed);

        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        B6.setBorder(null);
        B6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        B6.addActionListener(this::B6ActionPerformed);

        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        C1.setBorder(null);
        C1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        C1.addActionListener(this::C1ActionPerformed);

        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        C2.setBorder(null);
        C2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        C2.addActionListener(this::C2ActionPerformed);

        C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        C3.setBorder(null);
        C3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        C3.addActionListener(this::C3ActionPerformed);

        C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        C4.setBorder(null);
        C4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        C4.addActionListener(this::C4ActionPerformed);

        C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        C5.setBorder(null);
        C5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        C5.addActionListener(this::C5ActionPerformed);

        C6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        C6.setBorder(null);
        C6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        C6.addActionListener(this::C6ActionPerformed);

        D1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        D1.setBorder(null);
        D1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        D1.addActionListener(this::D1ActionPerformed);

        D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        D2.setBorder(null);
        D2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        D2.addActionListener(this::D2ActionPerformed);

        D3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        D3.setBorder(null);
        D3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        D3.addActionListener(this::D3ActionPerformed);

        D4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        D4.setBorder(null);
        D4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        D4.addActionListener(this::D4ActionPerformed);

        D5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        D5.setBorder(null);
        D5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        D5.addActionListener(this::D5ActionPerformed);

        D6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        D6.setBorder(null);
        D6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        D6.addActionListener(this::D6ActionPerformed);

        E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        E1.setBorder(null);
        E1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        E1.addActionListener(this::E1ActionPerformed);

        E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        E2.setBorder(null);
        E2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        E2.addActionListener(this::E2ActionPerformed);

        E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        E3.setBorder(null);
        E3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        E3.addActionListener(this::E3ActionPerformed);

        E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        E4.setBorder(null);
        E4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        E4.addActionListener(this::E4ActionPerformed);

        E5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        E5.setBorder(null);
        E5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        E5.addActionListener(this::E5ActionPerformed);

        E6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        E6.setBorder(null);
        E6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        E6.addActionListener(this::E6ActionPerformed);

        F1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        F1.setBorder(null);
        F1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        F1.addActionListener(this::F1ActionPerformed);

        F2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        F2.setBorder(null);
        F2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        F2.addActionListener(this::F2ActionPerformed);

        F3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        F3.setBorder(null);
        F3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        F3.addActionListener(this::F3ActionPerformed);

        F4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        F4.setBorder(null);
        F4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        F4.addActionListener(this::F4ActionPerformed);

        F5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        F5.setBorder(null);
        F5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        F5.addActionListener(this::F5ActionPerformed);

        F6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        F6.setBorder(null);
        F6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        F6.addActionListener(this::F6ActionPerformed);

        G1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        G1.setBorder(null);
        G1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        G1.addActionListener(this::G1ActionPerformed);

        G2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        G2.setBorder(null);
        G2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        G2.addActionListener(this::G2ActionPerformed);

        G3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        G3.setBorder(null);
        G3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        G3.addActionListener(this::G3ActionPerformed);

        G4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        G4.setBorder(null);
        G4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        G4.addActionListener(this::G4ActionPerformed);

        G5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        G5.setBorder(null);
        G5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        G5.addActionListener(this::G5ActionPerformed);

        G6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fueraserv.png"))); // NOI18N
        G6.setBorder(null);
        G6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionado.png"))); // NOI18N
        G6.addActionListener(this::G6ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("A");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("B");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("C");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("D");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("E");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("F");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("G");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("1");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("2");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("3");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("4");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("5");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("6");

        infovuelo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        nvuelo.setFont(new java.awt.Font("SimSun", 0, 48)); // NOI18N

        pagar.setBackground(new java.awt.Color(29, 152, 183));
        pagar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        pagar.setForeground(new java.awt.Color(255, 255, 255));
        pagar.setText("Pagar");
        pagar.setFocusPainted(false);
        pagar.addActionListener(this::pagarActionPerformed);

        volver.setBackground(new java.awt.Color(153, 153, 153));
        volver.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("Volver");
        volver.setFocusPainted(false);
        volver.addActionListener(this::volverActionPerformed);

        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("186106 - 186831 - 187012");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(212, 212, 212)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(G1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(G2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(G3)
                        .addGap(51, 51, 51)
                        .addComponent(G4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(G5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(G6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(A1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(A2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(A3)
                                .addGap(51, 51, 51)
                                .addComponent(A4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(A5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(A6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B3)
                                .addGap(51, 51, 51)
                                .addComponent(B4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B6))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(D1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(D2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(D3)
                                    .addGap(51, 51, 51)
                                    .addComponent(D4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(D5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(D6))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(E1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E3)
                                    .addGap(51, 51, 51)
                                    .addComponent(E4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E6))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(F1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(F2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(F3)
                                    .addGap(51, 51, 51)
                                    .addComponent(F4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(F5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(F6))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(C1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(C2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(C3)
                                    .addGap(51, 51, 51)
                                    .addComponent(C4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(C5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(C6))))
                        .addContainerGap(13, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(79, 79, 79)
                .addComponent(jLabel9)
                .addGap(80, 80, 80)
                .addComponent(jLabel10)
                .addGap(122, 122, 122)
                .addComponent(jLabel11)
                .addGap(79, 79, 79)
                .addComponent(jLabel12)
                .addGap(80, 80, 80)
                .addComponent(jLabel13)
                .addGap(67, 67, 67))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infovuelo, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(nvuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(660, 660, 660))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(G1)
                                .addComponent(G2)
                                .addComponent(G3)
                                .addComponent(G4)
                                .addComponent(G5)
                                .addComponent(G6))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(A1)
                                .addComponent(A2)
                                .addComponent(A3)
                                .addComponent(A4)
                                .addComponent(A5)
                                .addComponent(A6))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B2)
                                    .addComponent(B3)
                                    .addComponent(B4)
                                    .addComponent(B5)
                                    .addComponent(B6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(B1))
                                    .addComponent(nvuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(C2)
                                                .addComponent(C3)
                                                .addComponent(C4)
                                                .addComponent(C5)
                                                .addComponent(C6))
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(C1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel4)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(D1)
                                                        .addComponent(D2)
                                                        .addComponent(D3)
                                                        .addComponent(D4)
                                                        .addComponent(D5)
                                                        .addComponent(D6)))
                                                .addGap(12, 12, 12)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(E1)
                                                    .addComponent(E2)
                                                    .addComponent(E3)
                                                    .addComponent(E4)
                                                    .addComponent(E5)
                                                    .addComponent(E6)))
                                            .addComponent(jLabel5)))
                                    .addComponent(infovuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(F1)
                                    .addComponent(F2)
                                    .addComponent(F3)
                                    .addComponent(F4)
                                    .addComponent(F5)
                                    .addComponent(F6))
                                .addGap(35, 35, 35))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(72, 72, 72))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed

    }//GEN-LAST:event_A1ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A4ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A5ActionPerformed

    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A6ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B6ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C1ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C2ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C3ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C4ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C5ActionPerformed

    private void C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C6ActionPerformed

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D1ActionPerformed

    private void D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D2ActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D3ActionPerformed

    private void D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D4ActionPerformed

    private void D5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D5ActionPerformed

    private void D6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D6ActionPerformed

    private void E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E1ActionPerformed

    private void E2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E2ActionPerformed

    private void E3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E3ActionPerformed

    private void E4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E4ActionPerformed

    private void E5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E5ActionPerformed

    private void E6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E6ActionPerformed

    private void F1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F1ActionPerformed

    private void F2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F2ActionPerformed

    private void F3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F3ActionPerformed

    private void F4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F4ActionPerformed

    private void F5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F5ActionPerformed

    private void F6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F6ActionPerformed

    private void G1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G1ActionPerformed

    private void G2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G2ActionPerformed

    private void G3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G3ActionPerformed

    private void G4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G4ActionPerformed

    private void G5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G5ActionPerformed

    private void G6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G6ActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        new Vuelos(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarActionPerformed
        String[] filas = {"A", "B", "C", "D", "E", "F", "G"};
        int seleccionados = 0;
        List<String> lstAsientos = new ArrayList<>();

        for (int i = 0; i < asientos.length; i++) {
            if (asientos[i].isSelected() && asientos[i].isEnabled()) {

                // Calculamos el nombre del asiento (A1, A2... G6) según el índice i
                String letraFila = filas[i / 6];
                int numColumna = (i % 6) + 1;
                String nombreAsiento = letraFila + numColumna;
                
                registrarAsiento(nombreAsiento);
                seleccionados++;
                lstAsientos.add(nombreAsiento);
            }
        }

        if (seleccionados > 0) {
            String asientos = String.join(", ", lstAsientos);
            crearPDF(asientos,lstAsientos);
            
            new Vuelos(user).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione al menos un asiento para continuar.");
        }
    }//GEN-LAST:event_pagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Avion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton A1;
    private javax.swing.JToggleButton A2;
    private javax.swing.JToggleButton A3;
    private javax.swing.JToggleButton A4;
    private javax.swing.JToggleButton A5;
    private javax.swing.JToggleButton A6;
    private javax.swing.JToggleButton B1;
    private javax.swing.JToggleButton B2;
    private javax.swing.JToggleButton B3;
    private javax.swing.JToggleButton B4;
    private javax.swing.JToggleButton B5;
    private javax.swing.JToggleButton B6;
    private javax.swing.JToggleButton C1;
    private javax.swing.JToggleButton C2;
    private javax.swing.JToggleButton C3;
    private javax.swing.JToggleButton C4;
    private javax.swing.JToggleButton C5;
    private javax.swing.JToggleButton C6;
    private javax.swing.JToggleButton D1;
    private javax.swing.JToggleButton D2;
    private javax.swing.JToggleButton D3;
    private javax.swing.JToggleButton D4;
    private javax.swing.JToggleButton D5;
    private javax.swing.JToggleButton D6;
    private javax.swing.JToggleButton E1;
    private javax.swing.JToggleButton E2;
    private javax.swing.JToggleButton E3;
    private javax.swing.JToggleButton E4;
    private javax.swing.JToggleButton E5;
    private javax.swing.JToggleButton E6;
    private javax.swing.JToggleButton F1;
    private javax.swing.JToggleButton F2;
    private javax.swing.JToggleButton F3;
    private javax.swing.JToggleButton F4;
    private javax.swing.JToggleButton F5;
    private javax.swing.JToggleButton F6;
    private javax.swing.JToggleButton G1;
    private javax.swing.JToggleButton G2;
    private javax.swing.JToggleButton G3;
    private javax.swing.JToggleButton G4;
    private javax.swing.JToggleButton G5;
    private javax.swing.JToggleButton G6;
    private javax.swing.JLabel infovuelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nvuelo;
    private javax.swing.JButton pagar;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    public int[] estadoAsientos(String idV) {
        int[] asientos = new int[42];
        int idAvionRelacionado = -1;

        String sqlId = "SELECT id_vuelo FROM vuelos WHERE num_vuelo = ?";
        String sqlAsientos = "SELECT * FROM avion WHERE id_vuelo = ?";

        try (Connection con = DBConn.conectar()) {

            // Obtener el id_avion desde la tabla vuelos
            try (PreparedStatement ps1 = con.prepareStatement(sqlId)) {
                ps1.setString(1, idV);
                try (ResultSet rs1 = ps1.executeQuery()) {
                    if (rs1.next()) {
                        idAvionRelacionado = rs1.getInt("id_vuelo");
                    }
                }
            }

            // Si encontramos el id_avion, buscamos sus asientos
            if (idAvionRelacionado != -1) {
                try (PreparedStatement ps2 = con.prepareStatement(sqlAsientos)) {
                    ps2.setInt(1, idAvionRelacionado);
                    try (ResultSet rs2 = ps2.executeQuery()) {
                        if (rs2.next()) {
                            String[] filas = {"A", "B", "C", "D", "E", "F", "G"};
                            int contador = 0;

                            // Recorremos de la A a la G y del 1 al 6 para llenar el arreglo
                            for (String letra : filas) {
                                for (int i = 1; i <= 6; i++) {
                                    String nombreColumna = letra + i; 
                                    asientos[contador] = rs2.getInt(nombreColumna);
                                    contador++;
                                }
                            }
                        }
                    }
                }
            }
        } catch (SQLException e) {
            System.err.println("Error en la base de datos: " + e.getMessage());
        }

        return asientos;
    }
    
    private void cargarVuelo(String idV) {
        String sql = "SELECT * FROM vuelos WHERE num_vuelo = ?";

        try (Connection con = DBConn.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            
            ps.setString(1, idV);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    String destino = rs.getString("destino");
                    String fechaS = rs.getString("fecha_salida");
                    String horaS = rs.getString("hora_salida");
                    String fechaL = rs.getString("fecha_llegada");
                    String horaL = rs.getString("hora_llegada");
                    double precio = rs.getDouble("precio");
                    String puerta = rs.getString("puerta_salida");

                    nvuelo.setText("VUELO " + idV);
                
                    // Resumen para el usuario del vuelo
                    String infoHtml = "<html>" +
                            "<b>DETALLES DEL VUELO</b><br>" +
                            "Destino: " + destino + "<br>" +
                            "Fecha de Salida: " + fechaS + " " + horaS + "<br>" +
                            "Fecha de Llegada: " + fechaL + " " + horaL + "<br>" +
                            "Precio: $" + precio + "<br>" +
                            "Puerta: " + puerta +
                            "</html>";

                    infovuelo.setText(infoHtml);
                }
            }
        } catch (SQLException e) {
            System.err.println("Error al buscar detalles: " + e.getMessage());
        }
    }
    
    // Persistencia de datos
    public void actualizarMapaAsientos(String idVuelo) {
        dispo = estadoAsientos(idVuelo);
        
        ImageIcon iconOcupado = new ImageIcon(getClass().getResource("/img/ocupado.png"));

        for (int i = 0; i < 42; i++) {
            int estado = dispo[i];
            JToggleButton boton = asientos[i];

            if (estado != 0) { 
                boton.setDisabledIcon(iconOcupado);
                boton.setEnabled(false); 
                boton.setSelected(false);
            } 
        }
    }
    
    public void registrarAsiento(String nombreAsiento) {
        String sql = "UPDATE avion SET " + nombreAsiento + " = "
                   + "(SELECT id_usuario FROM usuarios WHERE user = ?), "
                   + "dispo = dispo - 1 "
                   + "WHERE id_vuelo = (SELECT id_vuelo FROM vuelos WHERE num_vuelo = ?)";

        try (Connection con = DBConn.conectar();
            PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, this.user); // Guardamos el ID del usuario
            ps.setString(2, this.idV);

            int filas = ps.executeUpdate();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error de base de datos: " + e.getMessage());
        }
    }
    
    public void liberarAsiento(String nombreAsiento) {
        String sql = "UPDATE avion SET " + nombreAsiento + " = 0, "
                   + "dispo = dispo + 1 "
                   + "WHERE id_vuelo = (SELECT id_vuelo FROM vuelos WHERE num_vuelo = ?)";

        try (Connection con = DBConn.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, this.idV);
            ps.executeUpdate();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error de base de datos al liberar asiento: " + e.getMessage());
        }
    }
    
    private PdfPCell crearCeldaDato(String label, String dato, Font fLabel, Font fDato) {
        PdfPCell cell = new PdfPCell();
        cell.setPadding(15);
        cell.setBorderColor(com.itextpdf.text.BaseColor.LIGHT_GRAY);
        cell.addElement(new Paragraph(label, fLabel));
        cell.addElement(new Paragraph(dato, fDato));
        return cell;
    }
    
    public void crearPDF(String asientos, List<String> lstAsientos){
        javax.swing.JTextField nombreT = new javax.swing.JTextField();
        javax.swing.JTextField tarjetaT = new javax.swing.JTextField();
        javax.swing.JTextField fechaT = new javax.swing.JTextField();
        javax.swing.JTextField cvvT = new javax.swing.JTextField();
            
        Object[] campos = {"Titular:", nombreT, "Tarjeta:", tarjetaT, "MM/AA:", fechaT, "CVV:", cvvT};
        boolean datosValidos = false;

        while (!datosValidos) {
            int op = javax.swing.JOptionPane.showConfirmDialog(this, campos, "Pago", javax.swing.JOptionPane.OK_CANCEL_OPTION);

            // Si el usuario presiona "Cancelar" o cierra la ventana con la 'X', salimos por completo
            if (op != javax.swing.JOptionPane.OK_OPTION) {
                for (String asiento : lstAsientos) {
                    liberarAsiento(asiento); // Cancelamos reserva
                } 
                
                return;     
            }

            try {
                String titular = nombreT.getText().trim();
                String tarjeta = tarjetaT.getText().trim();
                String fecha = fechaT.getText().trim();
                String cvv = cvvT.getText().trim();

                // validar nombre
                for (int i = 0; i < titular.length(); i++) {
                    char c = titular.charAt(i);
                    if (c >= '0' && c <= '9') {
                        throw new Exception("El nombre no puede contener números.");
                    }
                }

                // validar tarjeta
                if (tarjeta.length() != 6) {
                    throw new Exception("La tarjeta debe tener 6 números.");
                }
                for (int i = 0; i < tarjeta.length(); i++) {
                    char c = tarjeta.charAt(i);
                    if (c < '0' || c > '9') {
                        throw new Exception("La tarjeta solo debe contener números.");
                    }
                }

                // validar cvv
                if (cvv.length() != 3) {
                    throw new Exception("El CVV debe tener 3 números.");
                }
                for (int i = 0; i < cvv.length(); i++) {
                    char c = cvv.charAt(i);
                    if (c < '0' || c > '9') {
                        throw new Exception("El CVV solo debe contener números.");
                    }
                }

                // validar fecha
                if (fecha.length() != 5 || fecha.charAt(2) != '/') {
                    throw new Exception("La fecha debe tener formato MM/AA.");
                }

                try {
                    int mes = Integer.parseInt(fecha.substring(0, 2));
                    int anio = Integer.parseInt(fecha.substring(3, 5)) + 2000;

                    if (mes < 1 || mes > 12) {
                        throw new Exception("El mes (MM) debe ser un número válido entre 01 y 12.");
                    }

                    java.time.YearMonth actual = java.time.YearMonth.now();
                    int anioActual = actual.getYear();
                    int mesActual = actual.getMonthValue();

                    if (anio < anioActual || (anio == anioActual && mes < mesActual)) {
                        throw new Exception("La tarjeta ya está vencida. Debe ser posterior o igual a la fecha actual.");
                    }

                } catch (NumberFormatException e) {
                    throw new Exception("Los valores de mes y año deben ser puramente numéricos.");
                }

                datosValidos = true; 
                
                
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Validación", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
        
        String destino="", fecha_salida="", hora_salida="", fecha_llegada="", hora_llegada="";
        String puerta_salida="", puerta_embarque="", precio="", num_vuelo="";
        String nomb = user;
            
        try (Connection con = DBConn.conectar()) {
                
            // Datos del Vuelo
            PreparedStatement ps = con.prepareStatement("SELECT * FROM vuelos WHERE num_vuelo = ?");
            ps.setString(1, idV);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                destino = rs.getString("destino");
                fecha_salida = rs.getString("fecha_salida");
                hora_salida = rs.getString("hora_salida");
                fecha_llegada = rs.getString("fecha_llegada");
                hora_llegada = rs.getString("hora_llegada");
                puerta_salida = rs.getString("puerta_salida");
                puerta_embarque = rs.getString("puerta_embarque");
                precio = rs.getString("precio");
                num_vuelo = rs.getString("num_vuelo");
            }

            // Datos del Usuario
            PreparedStatement psU = con.prepareStatement("SELECT nombre, apellidoP, apellidoM FROM usuarios WHERE user = ?");
            psU.setString(1, user);
            ResultSet rsU = psU.executeQuery();
            
                if (rsU.next()) {
                    nomb = rsU.getString("nombre") + " " + rsU.getString("apellidoP") + " " + rsU.getString("apellidoM");
                }
                
        } catch (Exception e) {
            e.printStackTrace();
        }

        //GENERAR PDF
        Document document = new Document();
            
        try {
            String dest = "Ticket_Vuelo_" + idV + ".pdf";
            PdfWriter.getInstance(document, new FileOutputStream(dest));
            document.open();
            
            Font fontTitulo = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD, com.itextpdf.text.BaseColor.WHITE);
            Font fontLabel = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, com.itextpdf.text.BaseColor.GRAY);
            Font fontDato = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD, com.itextpdf.text.BaseColor.BLACK);
            com.itextpdf.text.BaseColor colorAzul = new com.itextpdf.text.BaseColor(29, 152, 183);

            //encabezado
            PdfPTable enc = new PdfPTable(2);
            enc.setWidthPercentage(100);
            enc.setWidths(new float[]{3, 1});

            //Celda de Texto encabezado lado izq
            PdfPCell cellT = new PdfPCell(new Paragraph("BOLETO DE ABORDAJE", fontTitulo));
            cellT.setBackgroundColor(colorAzul);
            cellT.setBorder(PdfPCell.NO_BORDER);
            cellT.setPadding(15);
            enc.addCell(cellT);

                //Celda encabezado que contendrá la Celda del Logo
                try {
                    java.net.URL logoUrl = getClass().getResource("/img/iconb.png");
                    Image logo = Image.getInstance(logoUrl);
                    logo.scaleToFit(30, 30);

                    //celda logo
                    PdfPTable celda_logo = new PdfPTable(1);
                    
                    //Celda específica del logo
                    PdfPCell logoin = new PdfPCell(logo);
                    logoin.setBorder(PdfPCell.NO_BORDER); // Quitar borde
                    logoin.setHorizontalAlignment(Element.ALIGN_RIGHT);
                    logoin.setPadding(10);
                    
                    // Metemos la celda logo en su tabla
                    celda_logo.addCell(logoin);
                    
                    // Finalmente, metemos esa tabla dentro de la celda header
                    PdfPCell headerLogo = new PdfPCell(celda_logo);
                    headerLogo.setBackgroundColor(colorAzul);
                    headerLogo.setBorder(PdfPCell.NO_BORDER);
                    headerLogo.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    
                    enc.addCell(headerLogo);
                } catch (Exception e) {
                    // Celda de respaldo en caso de error
                    PdfPCell empty = new PdfPCell(new Paragraph(num_vuelo, fontTitulo));
                    empty.setBackgroundColor(colorAzul);
                    empty.setBorder(PdfPCell.NO_BORDER);
                    enc.addCell(empty); }

            document.add(enc);

            //fila 1
            PdfPTable tabla1 = new PdfPTable(3);
            tabla1.setWidthPercentage(100);
            tabla1.addCell(crearCeldaDato("PASAJERO", nomb.toUpperCase(), fontLabel, fontDato));
            tabla1.addCell(crearCeldaDato("VUELO", idV, fontLabel, fontDato));
            tabla1.addCell(crearCeldaDato("DESTINO", destino, fontLabel, fontDato));
            document.add(tabla1);

            //fila 2
            PdfPTable tabla2 = new PdfPTable(2);
            tabla2.setWidthPercentage(100);
            tabla2.addCell(crearCeldaDato("SALIDA (" + fecha_salida + ")", hora_salida, fontLabel, fontDato));
            tabla2.addCell(crearCeldaDato("LLEGADA (" + fecha_llegada + ")", hora_llegada, fontLabel, fontDato));
            document.add(tabla2);
            
            //fila 3
            PdfPTable tabla3 = new PdfPTable(4);
            tabla3.setWidthPercentage(100);
            tabla3.addCell(crearCeldaDato("P. SALIDA", puerta_salida, fontLabel, fontDato));
            tabla3.addCell(crearCeldaDato("EMBARQUE", puerta_embarque, fontLabel, fontDato));
            tabla3.addCell(crearCeldaDato("ASIENTO(S)", asientos, fontLabel, fontDato));
            tabla3.addCell(crearCeldaDato("PRECIO", "$" + precio, fontLabel, fontDato));
            document.add(tabla3);
            
            document.add(new Paragraph("\nPresente este ticket digital al abordar.", fontLabel));
            document.close();
            
            Desktop.getDesktop().open(new File(dest));
        
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}