/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoaviones;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;

public class PDFUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PDFUser.class.getName());

    public PDFUser() {
        initComponents();
        this.setLocationRelativeTo(null); 
        
        cargarIdsUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        btnPDF = new javax.swing.JButton();
        vuelos = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(95, 15, 64));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("PDF User");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ID del usuario:");

        btnPDF.setBackground(new java.awt.Color(95, 15, 64));
        btnPDF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnPDF.setText("CREAR");
        btnPDF.setFocusPainted(false);
        btnPDF.addActionListener(this::btnPDFActionPerformed);

        vuelos.addActionListener(this::vuelosActionPerformed);

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("186106 - 186831 - 187012");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(vuelos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel11)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        int id = vuelos.getSelectedIndex();
        if (id <= 0){
            msg.setText("Seleccione un vuelo para ver detalles.");
        } else{
            generarPDF();
        }
    }//GEN-LAST:event_btnPDFActionPerformed

    private void vuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vuelosActionPerformed
        Object seleccionado = vuelos.getSelectedItem();

        if (seleccionado != null ) {
            mostrarResumen(seleccionado.toString());
        }
    }//GEN-LAST:event_vuelosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PDFUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel msg;
    private javax.swing.JComboBox<String> vuelos;
    // End of variables declaration//GEN-END:variables

    private void cargarIdsUsers() {
        // Consulta SQL para traer los id de los usuarios
        String sql = "SELECT id_usuario FROM usuarios ORDER BY id_usuario ASC";

        try (Connection con = DBConn.conectar();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            vuelos.removeAllItems();
            vuelos.addItem("ID...");
            while (rs.next()) {
                String num = rs.getString("id_usuario");
                vuelos.addItem(num);
            }

        } catch (SQLException e) {
            System.err.println("Error al cargar IDs en el ComboBox: " + e.getMessage());
    } }
    
    private void mostrarResumen(String idSeleccionado){
        if (vuelos == null || idSeleccionado.equals("Seleccione un usuario...")) {
            msg.setText("Seleccione un usuario para ver detalles.");
            return;
        }

        String sql = "SELECT * FROM usuarios WHERE id_usuario = ?";

        try (Connection con = DBConn.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {

            // Información de usuario
            ps.setString(1, idSeleccionado);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    String nombre = rs.getString("nombre");
                    String apeP = rs.getString("apellidoP");
                    String apeM = rs.getString("apellidoM");
                    String tel = rs.getString("tel");
                    String pasporte = rs.getString("num_pasaporte");

                    String infoHtml = "<html>" +
                            "<b>DETALLES DEL USUARIO</b><br>" +
                            "Nombre: " + nombre + " " + apeP + " " + apeM + "<br>" +
                            "Telefono: " + tel + "<br>" +
                            "Pasaporte: " + pasporte + "<br>" +
                            "</html>";

                    msg.setText(infoHtml);
                }
            }
        } catch (SQLException e) {
            System.err.println("Error al buscar detalles: " + e.getMessage());
    } }
    
    private PdfPCell crearCeldaDato(String label, String dato, Font fLabel, Font fDato) {
        PdfPCell cell = new PdfPCell();
        cell.setPadding(15);
        cell.setBorderColor(com.itextpdf.text.BaseColor.LIGHT_GRAY);
        cell.addElement(new Paragraph(label, fLabel));
        cell.addElement(new Paragraph(dato, fDato));
        return cell;
    }
    
    private void generarPDF() {
        String idSeleccionado = vuelos.getSelectedItem().toString();
        String nombreArchivo = "Usuario_" + idSeleccionado + ".pdf";
        String ruta = nombreArchivo;
        
        Font fontTitulo = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD, com.itextpdf.text.BaseColor.WHITE);
        Font fontLabel = new Font(Font.FontFamily.HELVETICA, 9, Font.NORMAL, com.itextpdf.text.BaseColor.GRAY);
        Font fontDato = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD, com.itextpdf.text.BaseColor.BLACK);
        com.itextpdf.text.BaseColor colorAzul = new com.itextpdf.text.BaseColor(29, 152, 183);
        
        
        Document document = new Document();

        try {
            PdfWriter.getInstance(document, new FileOutputStream(ruta));
            document.open();
            
            
            // T A B L A   1
            //Encabezado
            PdfPTable enc = new PdfPTable(2);
            enc.setWidthPercentage(100);
            enc.setWidths(new float[]{3, 1});

            //Celda de Texto encabezado lado izq
            PdfPCell cellT = new PdfPCell(new Paragraph("DATOS DEL USUARIO", fontTitulo));
            cellT.setBackgroundColor(colorAzul);
            cellT.setBorder(PdfPCell.NO_BORDER);
            cellT.setPadding(15);
            enc.addCell(cellT);

            //Celda encabezado que contendrá la Celda del Logo
            try {
                java.net.URL logoUrl = getClass().getResource("/img/iconb.png");
                Image logo = Image.getInstance(logoUrl);
                logo.scaleToFit(30, 30);

                //celda logo
                PdfPTable celda_logo = new PdfPTable(1);
                   
                //Celda específica del logo
                PdfPCell logoin = new PdfPCell(logo);
                logoin.setBorder(PdfPCell.NO_BORDER); // Quitar borde
                logoin.setHorizontalAlignment(Element.ALIGN_RIGHT);
                logoin.setPadding(10);
                    
                //Metemos la celda logo en su tabla
                celda_logo.addCell(logoin);
                    
                //Finalmente, metemos esa tabla dentro de la celda header
                PdfPCell headerLogo = new PdfPCell(celda_logo);
                headerLogo.setBackgroundColor(colorAzul);
                headerLogo.setBorder(PdfPCell.NO_BORDER);
                headerLogo.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    
                enc.addCell(headerLogo);
            } catch (Exception e) {
                // Celda de respaldo en caso de error
                PdfPCell empty = new PdfPCell(new Paragraph(idSeleccionado, fontTitulo));
                empty.setBackgroundColor(colorAzul);
                empty.setBorder(PdfPCell.NO_BORDER);
                enc.addCell(empty);
            }

            document.add(enc);           
            
            //SQL por ID
            String sql = "SELECT * FROM usuarios WHERE id_usuario = ?";

            try (Connection con = DBConn.conectar(); 
                 PreparedStatement ps = con.prepareStatement(sql)) {

                ps.setString(1, idSeleccionado);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    //Datos
                    String user = rs.getString("user");
                    String nombre = rs.getString("nombre");
                    String apellidoP = rs.getString("apellidoP");
                    String apellidoM = rs.getString("apellidoM");
                    String correo = rs.getString("correo");
                    String tel = rs.getString("tel");
                    String fechaN = rs.getString("fecha_nacimiento");
                    String nacionalidad = rs.getString("nacionalidad");
                    String num_pasaporte = rs.getString("num_pasaporte");
                    String tipo_usuario = rs.getString("tipo_usuario");

                    //Tabla
                    //Fila 1
                    PdfPTable fila1 = new PdfPTable(3);
                    fila1.setWidthPercentage(100);
                    
                    fila1.addCell(crearCeldaDato("ID DE USUARIO", idSeleccionado, fontLabel, fontDato));
                    fila1.addCell(crearCeldaDato("USUARIO", user, fontLabel, fontDato));
                    fila1.addCell(crearCeldaDato("NOMBRE COMPLETO", apellidoP + " " + apellidoM + " " + nombre, fontLabel, fontDato));
                    document.add(fila1);
                    
                    //Fila 2
                    PdfPTable fila2 = new PdfPTable(2);
                    fila2.setWidthPercentage(100);
                    
                    fila2.addCell(crearCeldaDato("CORREO", correo, fontLabel, fontDato));                   
                    fila2.addCell(crearCeldaDato("TELÉFONO", tel, fontLabel, fontDato));
                    document.add(fila2);
                    
                    //Fila 3
                    PdfPTable fila3 = new PdfPTable(4);
                    fila3.setWidthPercentage(100);
                    
                    fila3.addCell(crearCeldaDato("FECHA DE NACIMIENTO", fechaN, fontLabel, fontDato));
                    fila3.addCell(crearCeldaDato("NACIONALIDAD", nacionalidad, fontLabel, fontDato));                    
                    fila3.addCell(crearCeldaDato("NO. PASAPORTE", num_pasaporte, fontLabel, fontDato));
                    fila3.addCell(crearCeldaDato("TIPO DE USUARIO", tipo_usuario, fontLabel, fontDato));
                    document.add(fila3);
                }
            }
            
            
            // T A B L A   2
            //Encabezado
            PdfPTable enc2 = new PdfPTable(2);
            enc2.setWidthPercentage(100);
            enc2.setWidths(new float[]{3, 1});

            //Celda de Texto encabezado lado izq
            PdfPCell cellT2 = new PdfPCell(new Paragraph("RESERVAS PENDIENTES", fontTitulo));
            cellT2.setBackgroundColor(colorAzul);
            cellT2.setBorder(PdfPCell.NO_BORDER);
            cellT2.setPadding(15);
            enc2.addCell(cellT2);
            try {
                java.net.URL logoUrl = getClass().getResource("/img/iconb.png");
                Image logo = Image.getInstance(logoUrl);
                logo.scaleToFit(30, 30);

                //celda logo
                PdfPTable celda_logo = new PdfPTable(1);
                    
                //Celda específica del logo
                PdfPCell logoin = new PdfPCell(logo);
                logoin.setBorder(PdfPCell.NO_BORDER); // Quitar borde
                logoin.setHorizontalAlignment(Element.ALIGN_RIGHT);
                logoin.setPadding(10);
                    
                //Metemos la celda logo en su tabla
                celda_logo.addCell(logoin);
                    
                //Finalmente, metemos esa tabla dentro de la celda header
                PdfPCell headerLogo = new PdfPCell(celda_logo);
                headerLogo.setBackgroundColor(colorAzul);
                headerLogo.setBorder(PdfPCell.NO_BORDER);
                headerLogo.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    
                enc2.addCell(headerLogo);
            } catch (Exception e) {
                // Celda de respaldo en caso de error
                PdfPCell empty = new PdfPCell(new Paragraph(idSeleccionado, fontTitulo));
                empty.setBackgroundColor(colorAzul);
                empty.setBorder(PdfPCell.NO_BORDER);
                enc2.addCell(empty);
            }
            document.add(enc2);
            
            //Rerservas pendientes
            PdfPTable tablaR = new PdfPTable(5); 
            tablaR.setWidthPercentage(100);

            //Buscar al usuario en CUALQUIER columna de la tabla avion
            String[] letras = {"A", "B", "C", "D", "E", "F", "G"};
            StringBuilder sqlReservas = new StringBuilder();

            for (int i = 0; i < letras.length; i++) {
                for (int j = 1; j <= 6; j++) {
                    String colAsiento = letras[i] + j;
                    sqlReservas.append("SELECT v.num_vuelo, v.destino, v.fecha_salida, v.fecha_llegada, '").append(colAsiento).append("' as asiento ")
                                .append("FROM avion av ")
                                .append("JOIN vuelos v ON av.id_vuelo = v.id_vuelo ")
                                .append("WHERE av.").append(colAsiento).append(" = ? ");

                    if (!(i == letras.length - 1 && j == 6)) {
                        sqlReservas.append(" UNION ALL ");
                    }
                }
            }

            try (Connection con = DBConn.conectar();
                 PreparedStatement ps = con.prepareStatement(sqlReservas.toString())) {
                
                int totalAsientos = letras.length * 6;
                for (int k = 1; k <= totalAsientos; k++) {
                    ps.setString(k, idSeleccionado);
                }

                ResultSet rs = ps.executeQuery();
                boolean Reservas = false;

                while (rs.next()) {
                    Reservas = true;
                    
                    String vuelo = rs.getString("num_vuelo");
                    String destino = rs.getString("destino");
                    String fechaS = rs.getString("fecha_salida");
                    String fechaL = rs.getString("fecha_llegada");
                    String asiento = rs.getString("asiento");
                    
                    tablaR.addCell(crearCeldaDato("NO. VUELO", vuelo, fontLabel, fontDato));
                    tablaR.addCell(crearCeldaDato("DESTINO", destino, fontLabel, fontDato));
                    tablaR.addCell(crearCeldaDato("FECHA DE SALIDA", fechaS, fontLabel, fontDato));
                    tablaR.addCell(crearCeldaDato("FECHA DE LLEGADA", fechaL, fontLabel, fontDato));
                    tablaR.addCell(crearCeldaDato("ASIENTO", asiento, fontLabel, fontDato));
                }

                if (!Reservas) {
                    PdfPCell sinReservas = new PdfPCell(new Paragraph("No hay reservas", fontLabel));
                    sinReservas.setColspan(5);
                    sinReservas.setPadding(15);
                    sinReservas.setHorizontalAlignment(Element.ALIGN_CENTER);
                    sinReservas.setBorderColor(com.itextpdf.text.BaseColor.LIGHT_GRAY);
                    tablaR.addCell(sinReservas);
                }

                document.add(tablaR);

            } catch (SQLException e) {
                e.printStackTrace();
            }
            
            document.close();

            //Abrir archivo
            File archivo = new File(ruta);
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(archivo);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar PDF: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
}