/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoaviones;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahtzi
 */
public class Usuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Usuario.class.getName());
    String user;
    String iduss;
    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
    }
    
    public Usuario(String uss) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        user = uss;
        UsserText.setText("Usuario: "+ user);
        cargarVuelosProgramados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UsserText = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vuelos = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        UserPg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consola.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MIS VUELOS");

        UsserText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsserText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        vuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "VUELO", "DESTINO", "FECHA", "ASIENTOS", "CANCELAR"
            }
        ));
        vuelos.setRowHeight(30);
        jScrollPane2.setViewportView(vuelos);

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("186106 - 186831 - 187012");

        UserPg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retorno.png"))); // NOI18N
        UserPg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UserPg.setBorderPainted(false);
        UserPg.setContentAreaFilled(false);
        UserPg.setFocusable(false);
        UserPg.addActionListener(this::UserPgActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UserPg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(UsserText, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(UserPg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UsserText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserPgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPgActionPerformed
        new Vuelos(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UserPgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Usuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UserPg;
    private javax.swing.JLabel UsserText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable vuelos;
    // End of variables declaration//GEN-END:variables

    private void cargarVuelosProgramados() {
        
        String sql = "SELECT id_usuario FROM usuarios WHERE user = ?";

        try (Connection con = DBConn.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {

            // Información de usuario
            ps.setString(1, user);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    iduss = rs.getString("id_usuario");
                }
            }
        } catch (SQLException e) {
            System.err.println("Error al buscar detalles: " + e.getMessage());
        } 
        
        String[] letras = {"A", "B", "C", "D", "E", "F", "G"};
            StringBuilder sqlReservas = new StringBuilder("SELECT * FROM (");

            for (int i = 0; i < letras.length; i++) {
                for (int j = 1; j <= 6; j++) {
                    String colAsiento = letras[i] + j;
                    sqlReservas.append("SELECT v.num_vuelo, v.destino, v.fecha_salida, v.fecha_llegada, '").append(colAsiento).append("' as asiento ")
                                .append("FROM avion av ")
                                .append("JOIN vuelos v ON av.id_vuelo = v.id_vuelo ")
                                .append("WHERE av.").append(colAsiento).append(" = ? ");

                    if (!(i == letras.length - 1 && j == 6)) {
                        sqlReservas.append(" UNION ALL ");
                    }
                }
            }
            
            sqlReservas.append(") as temporal ORDER BY num_vuelo ASC, asiento ASC");

            try (Connection con = DBConn.conectar();
                 PreparedStatement ps = con.prepareStatement(sqlReservas.toString())) {
                
                int totalAsientos = letras.length * 6;
                for (int k = 1; k <= totalAsientos; k++) {
                    ps.setString(k, iduss);
                }

                ResultSet rs = ps.executeQuery();

            DefaultTableModel model = new DefaultTableModel(new Object[]{"Vuelo", "Destino", "Fecha Salida", "Asientos","Cancelar"}, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return column == 4;
                }
            };

            // Asignamos el nuevo modelo a JTable
            vuelos.setModel(model);
           // Limpiamos la tabla para que no se dupliquen los datos si se consultan varias veces
            model.setRowCount(0);
            
            while (rs.next()) {
                // Extraemos los datos de cada columna de la base de datos
                String num = rs.getString("num_vuelo");
                String destino = rs.getString("destino");
                String fecha = rs.getString("fecha_salida");
                String asiento = rs.getString("asiento");
               
                Object[] fila = {num, destino, fecha, asiento, "Cancelar"};
                model.addRow(fila);
            }
            
            vuelos.getColumnModel().getColumn(4).setCellRenderer(new RenderBoton());
            vuelos.getColumnModel().getColumn(4).setCellEditor(new EditorBoton(vuelos, new Runnable() {
            
            @Override
            public void run() {
                cargarVuelosProgramados();
            }   }));   
            
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al cargar los datos en la tabla");   }
    }
    
    private void cancelarAsientoEnBD(String nombreAsiento, String numVuelo) {
    // Ponemos en 0 el asiento de un avión asociado al número de vuelo recibido
    String sql = "UPDATE avion SET " + nombreAsiento + " = 0 "
               + "WHERE id_vuelo = (SELECT id_vuelo FROM vuelos WHERE num_vuelo = ?)";

    try (Connection con = DBConn.conectar();
         PreparedStatement ps = con.prepareStatement(sql)) {
        
        ps.setString(1, numVuelo);
        ps.executeUpdate();
        
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cancelar asiento: " + e.getMessage());
    }   }
    
    // Clase para DIBUJAR el botón en la tabla
    class RenderBoton extends javax.swing.JButton implements javax.swing.table.TableCellRenderer {
        public RenderBoton() {
            setText("Cancelar");
            setBackground(new java.awt.Color(95,15,64)); 
            setForeground(java.awt.Color.WHITE);
        }
        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, 
                boolean isSelected, boolean hasFocus, int row, int column) {
            return this;
        }   }

    // Clase para gestionar el CLIC del botón en la tabla
    class EditorBoton extends javax.swing.AbstractCellEditor implements javax.swing.table.TableCellEditor {
        private final javax.swing.JButton boton;

        public EditorBoton(javax.swing.JTable table, Runnable AlTerminar) {
            boton = new javax.swing.JButton("Cancelar");
            boton.setBackground(new java.awt.Color(220, 53, 69));
            boton.setForeground(java.awt.Color.WHITE);

            boton.addActionListener(e -> {
                int filaSeleccionada = table.getEditingRow();
                if (filaSeleccionada != -1) {
                    // Extrayemos los datos directamente de la fila donde se hizo clic
                    String numVuelo = table.getModel().getValueAt(filaSeleccionada, 0).toString();
                    String asientosStr = table.getModel().getValueAt(filaSeleccionada, 3).toString();

                    // Preguntamos confirmación al usuario
                    int respuesta = JOptionPane.showConfirmDialog(table, 
                        "¿Está seguro de que desea cancelar la reserva del vuelo " + numVuelo + "?", 
                        "Confirmar Cancelación", JOptionPane.YES_NO_OPTION);

                    if (respuesta == JOptionPane.YES_OPTION) {
                        // Separamos la cadena "A1, A2" en un arreglo para borrarlos uno por uno
                        String[] arrAsientos = asientosStr.split(", ");
                        for (String asiento : arrAsientos) {
                            // Llamamos al método del Paso 1
                            cancelarAsientoEnBD(asiento, numVuelo); 
                        }

                        JOptionPane.showMessageDialog(table, "Reserva cancelada y asientos liberados con éxito.");
                        fireEditingStopped(); // Detiene la edición de la celda
                        AlTerminar.run(); // Ejecuta la recarga de la tabla
                    } else {
                        fireEditingCanceled(); // Si dice que no, cancela la acción del botón
                    }
                }
            }); }

        @Override
        public java.awt.Component getTableCellEditorComponent(javax.swing.JTable table, Object value, boolean isSelected, int row, int column) {
            return boton;   }

        @Override
        public Object getCellEditorValue() {    return "Cancelar"; }   
    }
}
