/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoaviones;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Vuelos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vuelos.class.getName());
    String user;
    

    public Vuelos(String uss) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        user = uss;
        UsserText.setText("Usuario: "+ user);
        cargarVuelosProgramados();
        cargarIdsVuelos();
    }
    
    public Vuelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idVuelos = new javax.swing.JComboBox<>();
        resumen = new javax.swing.JLabel();
        disponibilidad = new javax.swing.JButton();
        TextWarning = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vuelos = new javax.swing.JTable();
        UsserText = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        UserPg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consola.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        jLabel2.setText("VUELOS");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setText("SELECCIONE EL ID DE SU VUELO: ");

        idVuelos.addActionListener(this::idVuelosActionPerformed);

        resumen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        disponibilidad.setBackground(new java.awt.Color(95, 15, 64));
        disponibilidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        disponibilidad.setForeground(new java.awt.Color(255, 255, 255));
        disponibilidad.setText("VER VUELO");
        disponibilidad.setFocusPainted(false);
        disponibilidad.addActionListener(this::disponibilidadActionPerformed);

        vuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "VUELO", "DESTINO", "FECHA"
            }
        ));
        jScrollPane2.setViewportView(vuelos);

        UsserText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsserText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("186106 - 186831 - 187012");

        UserPg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        UserPg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UserPg.setBorderPainted(false);
        UserPg.setContentAreaFilled(false);
        UserPg.setFocusable(false);
        UserPg.addActionListener(this::UserPgActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(131, 131, 131))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resumen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(idVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(disponibilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(TextWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(144, 144, 144))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(UsserText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UserPg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(UserPg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UsserText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(idVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resumen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disponibilidadActionPerformed
        Object selecc = idVuelos.getSelectedItem();
        
        if (selecc== null || selecc.toString().equals("ID...")) {
            TextWarning.setText("Seleccione un ID");
        } else {
            new Avion(user,selecc.toString()).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_disponibilidadActionPerformed

    private void idVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idVuelosActionPerformed
        Object seleccionado = idVuelos.getSelectedItem();
    
        if (seleccionado != null) {
            TextWarning.setText("");
            mostrarResumen(seleccionado.toString());
        }
    }//GEN-LAST:event_idVuelosActionPerformed

    private void UserPgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPgActionPerformed
        new Usuario(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UserPgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vuelos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextWarning;
    private javax.swing.JButton UserPg;
    private javax.swing.JLabel UsserText;
    private javax.swing.JButton disponibilidad;
    private javax.swing.JComboBox<String> idVuelos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel resumen;
    private javax.swing.JTable vuelos;
    // End of variables declaration//GEN-END:variables

    private void cargarVuelosProgramados() {
        // Definimos la consulta SQL con los campos específicos y el filtro
        String sql = "SELECT num_vuelo, destino, fecha_salida, hora_salida, precio " +
                     "FROM vuelos WHERE estado_vuelo = 'Programado'";
        try (Connection con = DBConn.conectar();
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery()) {
            DefaultTableModel model = new DefaultTableModel(new Object[]{"N° Vuelo", "Destino", "Fecha Salida"}, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    //Celdas solo de lectura
                    return false;
                }
            };
            // Asignamos el nuevo modelo a JTable
            vuelos.setModel(model);
           // Limpiamos la tabla para que no se dupliquen los datos si se consultan varias veces
            model.setRowCount(0);
            while (rs.next()) {
                // Extraemos los datos de cada columna de la base de datos
                String num = rs.getString("num_vuelo");
                String destino = rs.getString("destino");
                String fecha = rs.getString("fecha_salida");
                // Creamos un arreglo de objetos que representa una fila
                Object[] fila = {num, destino, fecha};
                // Agregamos la fila al modelo de la tabla
                model.addRow(fila);
            }
        } catch (SQLException e) {
           e.printStackTrace();
           JOptionPane.showMessageDialog(this, "Error al cargar los datos en la tabla");
        }
    }
    
    private void cargarIdsVuelos() {
        // Consulta SQL para traer solo los números de vuelo programados
        String sql = "SELECT num_vuelo FROM vuelos WHERE estado_vuelo = 'Programado'";

        try (Connection con = DBConn.conectar();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            idVuelos.removeAllItems();
            idVuelos.addItem("ID...");
            while (rs.next()) {
                String num = rs.getString("num_vuelo");
                idVuelos.addItem(num);
            }

        } catch (SQLException e) {
            System.err.println("Error al cargar IDs en el ComboBox: " + e.getMessage());
        }
    }
    
    private void mostrarResumen(String idSeleccionado){
        if (idVuelos == null || idSeleccionado.equals("Seleccione un vuelo...")) {
            resumen.setText("Seleccione un vuelo para ver detalles.");
            return;
        }
        String sql = "SELECT * FROM vuelos WHERE num_vuelo = ?";
        try (Connection con = DBConn.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, idSeleccionado);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    String destino = rs.getString("destino");
                    String fechaS = rs.getString("fecha_salida");
                    String horaS = rs.getString("hora_salida");
                    String fechaL = rs.getString("fecha_llegada");
                    String horaL = rs.getString("hora_llegada");
                    double precio = rs.getDouble("precio");

                    String infoHtml = "<html>" +
                            "<b>DETALLES DEL VUELO</b><br>" +
                            "Destino: " + destino + "<br>" +
                            "Fecha de Salida: " + fechaS + " " + horaS + "<br>" +
                            "Fecha de Llegada: " + fechaL + " " + horaL + "<br>" +
                            "Precio: $" + precio + "0" + "<br>" +
                            "</html>";

                    resumen.setText(infoHtml);
                }
            }
        } catch (SQLException e) {
            System.err.println("Error al buscar detalles: " + e.getMessage());
        }
    }
}